apiVersion: v1
kind: Service
metadata:
  name: api-peliculas
  labels:
    app: api-peliculas
spec:
  ports:
  - protocol: TCP
    port: 8001
    targetPort: http-server
  selector:
    app: api-peliculas
  type: LoadBalancer