apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 49160  
          env:
            - name: POSTGRES_HOST
              value: bubble.db.elephantsql.com
            - name: POSTGRES_DB
              value: sjmbhpsc
            - name: POSTGRES_USER
              value: sjmbhpsc
            - name: POSTGRES_PASSWORD
              value: Sx8H5Lk9V7S0mDZQEs0dz1mwubxO4nKt
